# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'XLActionControllerUse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XLActionControllerUse
	
	pod 'XLActionController'
    pod 'XLActionController/Periscope'
    pod 'XLActionController/Skype'
    pod 'XLActionController/Spotify'
    pod 'XLActionController/Tweetbot'
    pod 'XLActionController/Twitter'
    pod 'XLActionController/Youtube'
    

end
